version: "2"
checks:
  file-lines:
    config:
      threshold: 270  # default 250
  method-count:
    config:
      threshold: 30  # default 20
  method-lines:
    config:
      threshold: 40  # default 25
plugins:
  sonar-python:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
