name: workflow when PullRequest

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  pytest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: get dependencies
      uses: ./.github/actions/get_dependencies

    - name: linter
      uses: ./.github/actions/linter

    - name: build
      uses: ./.github/actions/build

    - name: test
      uses: ./.github/actions/test
